### ISSUE TITLE
[Feature request] Buttons above or below the graphics 

### ISSUE THREAD

**Issue by mailwash** [tungmeister/hass-blind-card#6]
It would be nice to have a possibility to show buttons in bottom and top position.

**Comment by luizcorreia** [comment]
You can try using card-mod to customize the layout. This worked for me:

```yaml
type: custom:blind-card
entities:
  - entity: cover.bedroom_blinds
    name: Master Bedroom
    buttons_position: left
    blind_color: '#333'
card_mod:
  style: |
    ha-card .sc-blind-middle {
      width: 100%;
      flex-direction: column-reverse !important;
    }
    ha-card .sc-blind-button + br {
      display: none;
    }
```
